spring:
  application:
    name: ms-clientes

server:
  port: 0 #setar para a porta 0 fará a instância subir em uma porta randomica

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} } #dará um valor randomico após nome do ms